[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
finitediff = "0.1.4"
mnist = "0.6.0"
ndarray = "0.15.6"
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.10.5"
